FROM nginx:alpine
RUN apk add --update bash && rm -rf /var/cache/apk/*
RUN rm /etc/nginx/conf.d/*
ADD conf.d/f5demo.template /etc/nginx/conf.d/
ADD conf.d/f5demo.js /etc/nginx/conf.d/
ADD conf.d/mime.types /etc/nginx/conf.d/
ADD nginx.conf /etc/nginx/nginx.conf
COPY server.crt /etc/nginx/server.crt
COPY server.key /etc/nginx/server.key
ADD nginx-foreground /usr/local/bin/nginx-foreground
COPY html /usr/share/nginx/html/
CMD /usr/local/bin/nginx-foreground
EXPOSE 443
